json.array!(@rfqs) do |rfq|
  json.extract! rfq, :id, :primaryKey, :RFQ_NUM, :RFQ_JOB_NUM, :RFQ_TASK, :RFQ_VENDOR_NUM, :RFQ_DATE, :RFQ_PROD_CONTACT, :RFQ_NAME, :RFQ_DESC, :RFQ_QTY, :RFQ_CLIENT_NUM, :RFQ_CLIENT_CONTACT, :RFQ_CLIENT_ADDR1, :RFQ_CLIENT_ADDR2, :RFQ_CLIENT_ADDR3, :RFQ_CLIENT_ADDR4, :RFQ_CLIENT_ADDR5, :RFQ_CLIENT_ADDR6, :RFQ_PREP, :RFQ_KITTING, :RFQ_SHIPPING, :RFQ_CLIENT_NOTES, :RFQ_TERMS, :RFQ_APPROVED, :RFQ_CLIENT_OK, :RFQ_CLIENT_OK_DATE, :RFQ_CLIENT_OK_BY, :RFQ_TOTAL_COST, :RFQ_TOTAL_GROSS, :RFQ_SPECIAL_INSTR, :RFQ_DEL_INSTR, :RFQ_AUTH, :RFQ_STATUS, :RFQ_ADDED_BY, :RFQ_QUOTE_NEEDED, :RFQ_DEL_DATE, :RFQ_PROD_CONTACT_EMAIL, :RFQ_TAXABLE1, :RFQ_TAXABLE2, :RFQ_PROD_CONTACT_PH
  json.url rfq_url(rfq, format: :json)
end
