json.array!(@meetings) do |meeting|
  json.extract! meeting, :id, :primaryKey, :MEET_DATE, :MEET_TIME, :MEET_ADDED_BY, :MEET_DURATION, :MEET_TOPIC, :MEET_OBJECTIVE, :MEET_DISCUSSION, :MEET_LOCATION, :MEET_DIRECTIONS, :MEET_ATTENDEES, :MEET_JOB_NUM, :MEET_ACTION_ITEMS, :MEET_FWD_SUM, :MEET_CC, :MEET_COORD, :MEET_CLIENT_NUM, :MEET_EMAIL_TO, :MEET_NOTIFY, :MEET_STATUS, :MEET_NEXT_DATE, :MEET_EDITED_BY, :MEET_EDITED_WHEN
  json.url meeting_url(meeting, format: :json)
end
