json.array!(@stations) do |station|
  json.extract! station, :id, :primaryKey, :PUB_CODE, :PUB_NAME, :PUB_REP, :PUB_PHONE, :PUB_ADDRESS1, :PUB_ADDRESS2, :PUB_ADDRESS3, :PUB_ADDRESS4, :PUB_NOTE, :PUB_FAX, :PUB_VENDOR_NUM, :PUB_COMM_PC, :PUB_TYPE, :PUB_REP_ADDRESS1, :PUB_REP_ADDRESS2, :PUB_REP_ADDRESS3, :PUB_REP_ADDRESS4, :PUB_REP_ADDRESS5, :PUB_ISSUE_DATE, :PUB_CLOSE_DATE, :PUB_CIRC, :PUB_MARKET, :PUB_ADDED_BY, :PUB_ADDED_WHEN, :PUB_EDITED_BY, :PUB_EDITED_WHEN
  json.url station_url(station, format: :json)
end
