json.array!(@je2s) do |je2|
  json.extract! je2, :id, :primaryKey, :JE2_DATE, :JE2_REF, :JE2_POSTED, :JE2_DESC, :JE2_DEBIT, :JE2_CREDIT, :JE2_AC_NUM, :JE2_PERIOD, :JE2_JOB_NUM, :JE2_CLIENT_NUM, :JE2_RECONCILE, :JE2_SOURCE, :JE2_ADDED_BY, :JE2_ADDED_WHEN, :JE2_VENDOR_NUM, :JE2_AUTO_REV, :JE2_AUTO_ACC, :JE2_TEMP_REC, :JE2_KIND, :JE2_PAY_BATCH, :JE2_GL_REC, :JE2_EXPORTED, :JE2_EDITED_BY, :JE2_EDITED_WHEN, :JE2_POSTED_BY, :JE2_POSTED_WHEN, :JE2_FISCAL_YEAR, :JE2_PERIOD_FIRST_DAY
  json.url je2_url(je2, format: :json)
end
