json.array!(@jes) do |je|
  json.extract! je, :id, :primaryKey, :JE_DATE, :JE_REF, :JE_POSTED, :JE_DESC, :JE_DEBIT, :JE_CREDIT, :JE_AC_NUM, :JE_PERIOD, :JE_JOB_NUM, :JE_CLIENT_NUM, :JE_RECONCILE, :JE_SOURCE, :JE_ADDED_BY, :JE_ADDED_WHEN, :JE_VENDOR_NUM, :JE_AUTO_REV, :JE_AUTO_ACC, :JE_TEMP_REC, :JE_KIND, :JE_PAY_BATCH, :JE_GL_REC, :JE_EXPORTED, :JE_EDITED_BY, :JE_EDITED_WHEN, :JE_POSTED_BY, :JE_POSTED_WHEN
  json.url je_url(je, format: :json)
end
