json.array!(@aps) do |ap|
  json.extract! ap, :id, :primaryKey, :AP_NUM, :AP_VENDOR_NUM, :AP_DATE, :AP_KEY, :AP_DESC, :AP_CGL, :AP_NET_AMT, :AP_COMM_NET, :AP_MARKUP_PC, :AP_TAX_AMT, :AP_GROSS_AMT, :AP_POSTED, :AP_TOTAL_AMT, :AP_DISC_DATE, :AP_JUMPSTART, :AP_ADDED_BY, :AP_ADDED_WHEN, :AP_VOUCHER, :AP_TERMS1, :AP_TERMS2, :AP_TERMS3, :AP_PAY_DATE, :AP_PERIOD, :AP_CURRENT, :AP_30, :AP_60, :AP_90, :AP_AUTO_PAY, :AP_GST_GL, :AP_GST1, :AP_GST2, :AP_AMT_PAID, :AP_CLIENT_PAID, :AP_CLOSE_PO, :AP_UNPAID, :AP_KIND, :AP_DISC_TAKEN, :AP_EXPORTED, :AP_APPROVED, :AP_APPROVED_BY, :AP_APPROVED_DATE, :AP_EDITED_BY, :AP_EDITED_WHEN, :AP_POSTED_BY, :AP_POSTED_WHEN, :AP_PAID_CC, :AP_DATE_PAID, :AP_PAID_CC_INV_NUM, :AP_PAID_ONLINE
  json.url ap_url(ap, format: :json)
end
