json.array!(@po_items) do |po_item|
  json.extract! po_item, :id, :primaryKey, :POX_LINE_NUMBER, :POX_JOB_NUM, :POX_TASK, :POX_DESC, :POX_PROGRAM, :POX_QTY, :POX_COST_EACH, :POX_COST, :POX_MARKUP, :POX_GROSS, :POX_COST_PAID, :POX_GROSS_PAID, :POX_PO_NUM, :POX_BILLABLE, :POX_UNIT, :POX_NAME, :POX_KEY, :POX_BUYDETID, :POX_DUE_DATE, :POX_DUE_DATE2, :POX_ISSUE_DATE, :POX_REVISION, :POX_AP_OK, :POX_AD_SIZE, :POX_AD_NAME, :POX_AR_NUM, :POX_PUB, :POX_CLIENT_NUM, :POX_BILL_NET, :POX_TYPE, :POX_RATING, :POX_CPP, :POX_CPM, :POX_MAKEGOOD, :POX_AR_AMT, :POX_COST_NUM, :POX_BILL_DATE, :POX_SALES_TAX, :POX_ISSUE_DATE2, :POX_TRADE, :POX_RUN_DATE, :POX_ADDED_BY, :POX_ADDED_WHEN, :POX_EDITED_BY, :POX_EDITED_WHEN, :POX_TAXABLE1, :POX_TAXABLE2
  json.url po_item_url(po_item, format: :json)
end
