json.array!(@proposals) do |proposal|
  json.extract! proposal, :id, :primaryKey, :PROPS_CLIENT_NUM, :PROPS_DATE_ADDED, :PROPS_REQUESTOR, :PROPS_TYPE, :PROPS_BUDGET, :PROPS_START_DATE, :PROPS_DUE_DATE, :PROPS_OK_BY, :PROPS_CB1, :PROPS_CB2, :PROPS_CB3, :PROPS_CB4, :PROPS_CB5, :PROPS_CB6, :PROPS_CB7, :PROPS_CB8, :PROPS_CB9, :PROPS_CB10, :PROPS_CB11, :PROPS_CB12, :PROPS_CB13, :PROPS_CB14, :PROPS_CB15, :PROPS_NAME, :PROPS_OK_DATE, :PROPS_DESC, :PROPS_CHARGE_NUM, :PROPS_STATUS_DESC, :PROPS_STATUS, :PROPS_ADDED_BY, :PROPS_APPROVED, :PROPS_APPROVED_BY, :PROPS_APPROVED_DATE, :PROPS_EDITED_BY, :PROPS_EDITED_WHEN, :PROPS_REVIEWER
  json.url proposal_url(proposal, format: :json)
end
