json.array!(@checks) do |check|
  json.extract! check, :id, :primaryKey, :CK_NUM, :CK_VENDOR_NUM, :CK_PAYEE, :CK_ADDRESS1, :CK_ADDRESS2, :CK_ADDRESS3, :CK_DATE, :CK_POSTED, :CK_MEMO, :CK_NET_AMT, :CK_CGL, :CK_PAY, :CK_ADDED_BY, :CK_ADDED_WHEN, :CK_CLEARED, :CK_DONT_PRINT, :CK_AMOUNT, :CK_TYPE, :CK_GROSS, :CK_DISC_AMT, :CK_DISC_GL, :CK_OK, :CK_PERIOD, :CK_1099, :CK_TAX_ID, :CK_EMP_ADV_EXP, :CK_EMPL_ADV_CK, :CK_EDITED_BY, :CK_EDITED_WHEN, :CK_POSTED_BY, :CK_POSTED_WHEN, :CK_ONLINE_PMT_CONFIRM_NUM
  json.url check_url(check, format: :json)
end
